"""Created accessibility enum for use in event and group tables

Revision ID: 1c2565344194
Revises: d5bf8428057a
Create Date: 2020-06-21 23:19:45.454991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2565344194'
down_revision = 'd5bf8428057a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE accessibility AS ENUM ('private', 'public');")
    op.add_column('event', sa.Column('accessibility', sa.Enum('public', 'private', name='accessibility'), nullable=False))
    op.add_column('group', sa.Column('accessibility', sa.Enum('public', 'private', name='accessibility'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'accessibility')
    op.drop_column('event', 'accessibility')
    op.execute('DROP TYPE accessibility;')
    # ### end Alembic commands ###
