"""Dropped time fields from intermediary tables

Revision ID: 89dd2581a253
Revises: 32bcc375e5eb
Create Date: 2020-06-22 20:19:11.572458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '89dd2581a253'
down_revision = '32bcc375e5eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_group', 'deleted_at')
    op.drop_column('event_group', 'updated_at')
    op.drop_column('event_group', 'created_at')
    op.drop_column('profile_selection', 'deleted_at')
    op.drop_column('profile_selection', 'updated_at')
    op.drop_column('profile_selection', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_selection', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('profile_selection', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('profile_selection', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_group', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_group', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('event_group', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
